version: '3'
services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - USE_SPACES=TRUE
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_STORAGE_BUCKET_NAME=

      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=

      - SOCIAL_AUTH_FACEBOOK_KEY=
      - SOCIAL_AUTH_FACEBOOK_SECRET=

      - OTP_SECRET_KEY=
      - OTP_EXPIRES=1800

      - EMAIL_DEFAULT=
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=


    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py makemigrations &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
               
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
