version: '3'
services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - USE_SPACES=TRUE
      - AWS_ACCESS_KEY_ID=DO002LR3V76BCZ6MH4XT
      - AWS_SECRET_ACCESS_KEY=WBrGHQEAQZv1euK3n/MOisMrnALDesjAPkMj1nkxx1M
      - AWS_STORAGE_BUCKET_NAME=postatusapistorage

      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=565700308053-virs9lpblofiu6b0rq9bpkb7drgqse1p.apps.googleusercontent.com
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=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

      - SOCIAL_AUTH_FACEBOOK_KEY=783561869389000
      - SOCIAL_AUTH_FACEBOOK_SECRET=73c8e6c8354eb096ad451e5ef1f0ec02

      - OTP_SECRET_KEY=ZQ7ZK6WKO5BEWVK46GFNBI64JKGBNJ57
      - OTP_EXPIRES=1800

      - EMAIL_DEFAULT=support@phoneflag.com
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_HOST_USER=sodiqb86@gmail.com
      - EMAIL_HOST_PASSWORD=dpxrdcjpiyusfdax


    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py makemigrations &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
               
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
